/******CATEGORÍA****/
INSERT INTO  categoria (categoria) VALUES ('Cabello'), ('Cuerpo'), ('Cuidado dental'), ('Protección Solar'), ('Cara');
/*****SECCION*****/
INSERT INTO seccion (seccion) VALUES ('Todos los productos'),('Más vendidos'), ('Carrusel'), ('Búsqueda'), ('Banner'), ('Descuentos');
/*****MODO DE USO *****/
INSERT INTO modo_de_uso (modo_de_uso) VALUES ('FROTAR LA BARRA HÚMEDA EN LAS MANOS Y USAR LA ESPUMA RESULTANTE PARA LAVAR EL CABELLO.'), ('FROTAR LA BARRA EN LAS MANOS O DIRECTAMENTE SOBRE EL CABELLO DE MEDIAS A PUNTAS.'), ('FROTAR LA BARRA SOBRE LA ZONA DESEADA Y ESPARCIR EL PRODUCTO CON LAS MANOS.'),('HUMEDECE TU CEPILLO Y FRÓTALO SOBRE LA TABLETA, CEPILLA COMO DE COSTUMBRE Y ENJUAGA CON AGUA.'),('FROTAR LA BARRA SOBRE LA ZONA DESEADA Y ESPARCIR EL PRODUCTO CON LAS MANOS.'),('USAR UNA GOTA DE PRODUCTO Y DAR UN LIGERO MASAJE SOBRE LA ZONA DESEADA');
/*****PRESENTACIÓN*****/
INSERT INTO presentacion (presentacion) VALUES ('Chico'), ('Grande');
/*****IMAGEN PRODUCTO*****/
INSERT INTO imagen_producto (imagen) VALUES ('https://i.ibb.co/zsbz5f9/S000-1.jpg;'),('https://i.ibb.co/jVJLPRS/S000-2.jpg'),('https://i.ibb.co/GtVyW49/S001-3.jpg'),('https://i.ibb.co/f41k5r4/S001-4.png'),('https://i.ibb.co/v31KMGM/S002-1.jpg')('https://i.ibb.co/LtrxvpR/S004-2.jpg'),('https://i.ibb.co/C9pkwFG/S005-1.jpg'),('https://i.ibb.co/cCRBFXt/B000-1.jpg'),('https://i.ibb.co/s9xGLTD/A000-1.jpg'),('https://i.ibb.co/ZMpq4jG/C000-1.jpg'),('https://i.ibb.co/SBW16hr/C000-2.jpg'),('https://i.ibb.co/F7mKrzK/C000-3.jpg'),('https://i.ibb.co/Wsdy5Nz/C000-4.jpg'),('https://i.ibb.co/t3QBGsL/C001-1.jpg'),('https://i.ibb.co/yBB1qqq/C001-2.jpg'),('https://i.ibb.co/KLm8bWD/H001-1.jpg'),('https://i.ibb.co/rFcx6RJ/H001-2.jpg'),('https://i.ibb.co/G3QJZBD/C005-1.jpg'),('https://i.ibb.co/cXysssP/P000-1.jpg'),('https://i.ibb.co/QpNgKjF/P000-2.jpg'),('https://i.ibb.co/yY7hWQ8/P001-1.jpg'),('https://i.ibb.co/nLgqVKg/H002-1.jpg'),('https://i.ibb.co/zxQ2DD1/F002-1.jpg'),('https://i.ibb.co/G9kVWH2/F002-2.jpg'),('https://i.ibb.co/PrG2D5z/F002-3.jpg'),('https://i.ibb.co/gyNX6pB/F002-4.jpg'),('https://i.ibb.co/BjCx6Kx/D000-1.jpg'),('https://i.ibb.co/26bNc34/D002-1.jpg'),('https://i.ibb.co/mXJFyn6/D003-1.jpg'),('https://i.ibb.co/kmxqv78/J000-1.jpg'),('https://i.ibb.co/fNWXy8H/J001-1.jpg'),('https://i.ibb.co/zHWy0PG/J002-1.jpg'),('https://i.ibb.co/M20Zh9M/J003-1.png');
/*****ESTADO*****/
INSERT INTO estado (estado) VALUES ('Aguascalientes'), ('Baja California'), ('Baja California Sur'), ('Campeche'), ('Ciudad de Mèxico'), ('Chiapas'), ('Chihuahua'), ('Coahuila de Zaragoza'), ('Colima'), ('Durango'), ('Guanajuato'), ('Guerrero'), ('Hidalgo'), ('Jalisco'), ('México'), ('Michoacán de Ocampo'), ('Morelos'), ('Nayarit'), ('Nuevo León'), ('Oaxaca de Juárez'), ('Puebla'), ('Querétaro'), ('Quintana Roo'), ('San Luis Potosí'), ('Sinaloa'), ('Sonora'), ('Tabasco'), ('Tamaulipas'), ('Tlaxcala'), ('Veracruz de Ignacio de la Llave'), ('Yucatán'), ('Zacatecas');
/*****BLOG*****/
INSERT INTO blog (fecha, contenido, categoria_blog, titulo, resumen) VALUES ('2022-08-22','Lorem, ipsum  velit actaque!', 'tips','BAÑATE COMO HOMBRE', 'Lorem, ipsum dolor sit amet doloribus, obcaecati velit');
/****IMAGEN BLOG****/
INSERT INTO imagen_blog (imagen, blog_id_blog) VALUES ('https://i.ibb.co/sw3XmFM/50-3.png\', '1');
/****CONTACTO*****/
INSERT INTO contacto (asunto_cn, comentario, nombre_cn, telefono_cn) VALUES ('hola, asdasdfasfada', 'asDFASDFSDAFDFASDFDSAAF', 'Ollin', '55398531');
/****PRODUCTOS****/
INSERT INTO productos VALUES ('Gracias a las propiedades anticépticas y cicatrizantes de caléndula (Calendula officinalis) este shampoo ayuda con afecciones en la piel como brotes (acné/alergias). Evita la resequedad debido a su protección el cuero cabelludo de los cambios ambientales.','Sodium Cocoyl Isethionate, Agua destilada, Pétalos de Caléndula, Oleato de Caléndula, Caolín, Manteca de coco, Glicerina Vegetal y Pantenol.',40,'SHAMPOO DE CALÉNDULA',90,'S000',1,1,1);
INSERT INTO productos VALUES ('La jamaica (Hibiscus sabdarifa) es una planta que nos brinda una variedad de beneficios dependiendo de su presentación, tiene un alto contenido de vitamina A, C, E Y B1 , en el caso de la piel ayuda a nutrir el cabello brindándole fuerza y brillo natural, evita la caída y previene el envejecimiento prematuro.','Sodium Cocoyl Isethionate, Agua destilada, sépalos de Jamaica, Oleato de Jamaica, Caolín, Manteca de coco, Glicerina Vegetal y Pantenol.',35,'SHAMPOO DE JAMAICA',90,'S001',1,1,1);
INSERT INTO productos VALUES ('Nuestro Shampoo de Romero es de los favoritos, gracias a las propiedades antioxidantes y dermoprotectoras ayudan a fortalecer el cuero cabelludo, estimula el crecimiento del cabello, brinda color y brillo natural, evita la resequedad y caída.','Sodium Cocoyl Isethionate, Agua destilada, Hojas de Romero, Oleato de Romero, Caolín, Manteca de coco, Glicerina Vegetal y Pantenol.',51,'SHAMPOO DE ROMERO',90,'S002',1,1,1);
INSERT INTO productos VALUES ('Las propiedades nutritivas de los frutos en la piel contribuyen a la producción de colágeno, brindan suavidad en la piel y el cabello, aportan brillo natural, protegen de cambios físicos, además de un aroma fresco y dulce.','Sodium Cocoyl Isethionate, Agua destilada, Mezcla de Frutos rojos deshidratados, Aceite de frambuesa, Caolín, Manteca de coco, Glicerina Vegetal y Pantenol.',17,'SHAMPOO DE FRUTOS ROJOS',90,' S004',1,1,1);
INSERT INTO productos VALUES ('La combinación de romero, aceite escencial y flores de lavanda (Lavanda angustifolia) hacen a este shampoo tan especial, tiene un efecto terapéutico por sus propiedades aromáticas tanto del romero como de la lavanda, ayuda con padecimientos como estrés, ansiedad o depresión, calmando los síntomas físicos que éstos puedan generar. En cuanto a la piel: aportan brillo, suavidad, tiene propiedades anticépticas por lo que previene cualquier tipo de afecciones.','Sodium Cocoyl Isethionate, Agua destilada, Pétalos de caléndula, Oleato de caléndula, Caolín, Manteca de coco, Glicerina Vegetal y Pantenol.',23,'SHAMPOO DE LAVANDA',90,'S005',1,1,1);
INSERT INTO productos VALUES ('Gracias a las propiedades anticépticas y cicatrizantes de Calendula officinalis este shampoo ayuda con afecciones en la piel como brotes (acné/alergias) y evita la resequedad debido a su protección el cuero cabelludo de los cambios ambientales.','Sodium Cocoyl Isethionate, Agua destilada, Pétalos de Calendula, Oleato de Calendula, Caolín, Manteca de coco, Glicerina Vegetal y Pantenol.',19,'SHAMPOO DE CALENDULA GRANDE',150,B000,1,1,2);
INSERT INTO productos VALUES ('Elaborado a base de mantecas vegetales y aceite escencial de toronja, es rico en vitamina E y B1 por lo que protege el cabello de la desecacion causada por agentes fisicos externos, previene la aparicion de puntas abiertas y deja un aroma fresco y suave a toronja.','Cera acondicionadora, Alcohol Cetílico, Manteca de cacao, Manteca de Coco, Aceite escencial de toronja y Vitamina E.',8,'ACONDICIONADOR CÍTRICOS',87,'A000',1,2,1);
INSERT INTO productos VALUES ('Nuestra crema hidratante es puramente nutritiva, ayuda con la aparición de estrías gracias a los acidos grasos de la manteca de coco y cacao, es regenerante gracias a las propiedades del oleato de caléndula por lo que ayuda a cicatriar heridas provocadas por agentes físicos externos.','Manteca de Cacao, Oleato de Caléndula, Manteca de Coco, Cera de Candelilla, Cera emulsionante y Vitamina E.',14,'CREMA CORPORAL CACAO',100,'C000',2,3,1);
INSERT INTO productos VALUES ('Nuestra crema hidratante es puramente nutritiva, ayuda con la aparición de estrías gracias a los acidos grasos de la manteca de coco y cacao, es regenerante gracias a las propiedades del oleato de caléndula por lo que ayuda a cicatriar heridas provocadas por agentes físicos externos.','Manteca de Cacao, Oleato de Caléndula, Manteca de Coco, Cera de Candelilla, Cera emulsionante y Vitamina E.',7,'CREMA CORPORAL CACAO',140,'C001',2,3,2);
INSERT INTO productos VALUES ('Crema hecha a base de mantecas nutritivas y aceites escenciales, aporta suavidad y brillo mientras protege de las picaduras o mordeduras de insectos como moscas y mosquitos. Esta presentación es ideal para llevar en el bolsillo.','Manteca de Cacao, Manteca de Mango, Oleato de Manzanilla, Cera de Candelilla, Aceite esencial de citronela, Aceite esencial de clavo, Aceite esencial de lavanda y Vitamina E.',32,'CREMA REPELENTE DE INSECTOS',145,'H001',2,3,1);
INSERT INTO productos VALUES ('Crema hecha a base de mantecas nutritivas y aceites escenciales, aporta suavidad y brillo mientras protege de las picaduras o mordeduras de insectos como moscas y mosquitos. Esta presentación es ideal para tocador o llevar de viaje.','Manteca de Cacao, Manteca de Mango, Oleato de Manzanilla, Cera de Candelilla, Aceite esencial de citronela, Aceite esencial de clavo, Aceite esencial de lavanda y Vitamina E.',24,'CREMA REPELENTE DE INSECTOS',140,'C005',2,3,2);
INSERT INTO productos VALUES ('Contar con una protección fisica a los rayos solares sin afectar el ambiente dónde vas a disfrutar de la naturaleza es vital en nuestro tiempo, es por eso que nuestro protector solar esta elaborado a base de ingredientes naturales, brindandote la protección que necesitas sin contaminar el entorno.','Manteca de mango, Cera de candelilla, Manteca de karité, Aceite de oliva, Aceite de zanahoria, Dioxido de titanio, Oxido de zinc, Alcohol cetílico, Vitamina E y Vitamina C.',46,'PROTECTOR SOLAR',190,'P000',4,3,2);
INSERT INTO productos VALUES ('Contar con una protección fisica a los rayos solares sin afectar el ambiente dónde vas a disfrutar de la naturaleza es vital en nuestro tiempo, es por eso que nuestro protector solar está elaborado a base de ingredientes naturales, brindandote la protección que necesitas sin contaminar el entorno.','Manteca de mango, Cera de candelilla, Manteca de karité, Aceite de oliva, Aceite de zanahoria, Dioxido de titanio, Oxido de zinc, Alcohol cetílico, Vitamina E y Vitamina C.',27,'PROTECTOR SOLAR',152,'H002',4,3,1); 
INSERT INTO productos VALUES ('Elaborado a base de aceites concentrados que tienen propiedades vasodilatadoras, este suero ayuda con el crecimiento de vello, puede usarse de día o de noche ya que no mancha la piel.Sin embargo, se recomienda su uso nocturno para tener resultados más rápido.’,’Aceite de ricino, Aceite de Semilla de Mamey, Oleato de Romero, Vitamina E.’,80, ‘SUERO FORTALECEDOR DE VELLO’,90,’F002’,5,6,1);
